components:
  schemas:
    ConversationRequest:
      description: Request message to Carplus.
      properties:
        message:
          title: Message
          type: string
      required:
      - message
      title: ConversationRequest
      type: object
    ConversationResponse:
      description: Deployed Carplus response.
      properties:
        response:
          title: Response
          type: string
      required:
      - response
      title: ConversationResponse
      type: object
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
  securitySchemes:
    HTTPBearer:
      scheme: bearer
      type: http
info:
  description: This plugin provides access to a QA Bot to answer questions about services
    provided by Carplus, a ride-sharing company in Taiwan.
  title: "\u683C\u4E0A\u5C0F\u5E6B\u624B"
  version: 1.0.0
openapi: 3.0.2
paths:
  /ask-carplus:
    post:
      description: "Ask questions about \u683C\u4E0A\u79DF\u8ECA's services!"
      operationId: chat_ask_carplus_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConversationRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversationResponse'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      security:
      - HTTPBearer: []
      summary: Chat
servers:
- url: http://0.0.0.0:8080
